CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/gaussian_noise_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/shot_noise_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/impulse_noise_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&

CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/defocus_blur_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/glass_blur_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/motion_blur_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/zoom_blur_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&

CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/snow_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/frost_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/fog_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/brightness_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&

CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/contrast_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/elastic_transform_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/pixelate_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1 &&
CUDA_VISIBLE_DEVICES=$5 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/test-C-10/jpeg_compression_5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 $4 0 --model resnet26_dwt_se --lr 0.1 --epochs 1 --sched cosine -b 128 -j 15 --val-split val --input-size 3 224 224 --output $3 --num-classes 10 --experiment TEST2 --no-prefetcher --resume $2 --ada 1 --lbatch $1
