CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/gaussian_noise/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/shot_noise/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/impulse_noise/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&

CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/defocus_blur/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/glass_blur/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/motion_blur/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/zoom_blur/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&

CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/snow/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/frost/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/fog/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/brightness/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&

CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/contrast/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/elastic_transform/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/pixelate/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3 &&
CUDA_VISIBLE_DEVICES=$1 python train_dwt_tta_se_lifelong_setting.py /home/oem/servers/imagenet-c/jpeg_compression/5 --dwt-kernel-size 3 3 3 --dwt_level 2 2 2 --dwt_bn 1 321 0 --model resnet50_dwt_se --lr 0.05 --epochs 1 --sched cosine -b 128 -j 5 --val-split val --input-size 3 224 224 --output $4 --num-classes 1000 --experiment TEST --no-prefetcher --resume $5 --ada 1 --lbatch $2 --seed $3
